server:
  port: 9999


#mapper-locations: classpath*:mapper/*.xml
#              #实体扫描，多个package用逗号或者分号分隔
#typeAliasesPackage: freak.bean
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.172:3306/freak?characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: freak
#    password: freak
#    driverClassName: com.mysql.jdbc.Driver

